### ISSUE TITLE
Algo/ReadMe

### ISSUE THREAD

**Issue by violentdelight** [Hsankesara/MyMachine#31]
This issue is about
  - [x] Algorithm
  - [ ] Project
  - [ ] Resources
    - [ ] Add new resource
    	- [ ] Course
        - [ ] Language support
        - [ ] Podcasts
        - [ ] Books 
        - [ ] tools
        - [ ] Links to other git repo
    - [ ] Curate existing resources
    	- [ ] Course
        - [ ] Language support
        - [ ] Podcasts
        - [ ] Books 
        - [ ] tools
        - [ ] Links to other git repo
  - [ ] Bug fixes
- [ ] Issue Title is in form `Algo/Project Name [Language]`.
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/Project is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.

 It's not necessary for all for points to be checked, we will look upon what is required once you open an issue.

**Comment by violentdelight** [comment]
Shouldn't we include a deadline in the the Algos section?, such that if someone commits to something they must complete it in a given deadline after which they have to be either reassigned the issue or the issue would be closed.

**Comment by Hsankesara** [comment]
@shivamsaboo17  Please add this feature in PR Template file.

**Comment by Hsankesara** [comment]
Thank you @violentdelight  for your suggestion.

**Comment by shivamsaboo17** [comment]
@Hsankesara shouldn't this be added in issue template?

**Comment by Hsankesara** [comment]
Oh My bad on issue template... 😓
