### ISSUE TITLE
Create a logo 

### ISSUE THREAD

**Issue by guru-DeV-002** [Hsankesara/MyMachine#36]
This issue is about

  - [ ] Algorithm
  - [ ] Project
  - [ ] Resources
    - [ ] Add new resource
    	- [ ] Course
        - [ ] Language support
        - [ ] Podcasts
        - [ ] Books 
        - [ ] tools
        - [ ] Links to other git repo
    - [ ] Curate existing resources
    	- [ ] Course
        - [ ] Language support
        - [ ] Podcasts
        - [ ] Books 
        - [ ] tools
        - [ ] Links to other git repo
  - [ ] Bug fixes
- [ ] Issue Title is in form `Algo/Project Name [Language]`.
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/Project is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be un-assigned from an issue if I do not work on it for a week.
 It's not necessary for all for points to be checked, we will look upon what is required once you open an issue.

**Comment by khilanravani** [comment]
Gitter channel created and linked with this repo. Will add the badges shortly.

**Comment by khilanravani** [comment]
So sorry...closed the wrong issue. 😓
