### ISSUE TITLE
Travis failed due to kmeans.py

### ISSUE THREAD

**Issue by Hsankesara** [Hsankesara/MyMachine#51]
This issue is about
  - [ ] Algorithm
  - [ ] Project
  - [ ] Resources
    - [ ] Add new resource
    	- [ ] Course
        - [ ] Language support
        - [ ] Podcasts
        - [ ] Books 
        - [ ] tools
        - [ ] Links to other git repo
    - [ ] Curate existing resources
    	- [ ] Course
        - [ ] Language support
        - [ ] Podcasts
        - [ ] Books 
        - [ ] tools
        - [ ] Links to other git repo
  - [x] Bug fixes
- [ ] Issue Title is in form `Algo/Project Name [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This Algo/Project is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
	- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [ ] I understand that I will be un-assigned from an issue if I do not work on it for a week.
 It's not necessary for all for points to be checked, we will look upon what is required once you open an issue.

**Comment by Hsankesara** [comment]
@guru-DeV-002 have a look.

**Comment by shivamsaboo17** [comment]
Try writing future import on the first line of the code.

**Comment by Hsankesara** [comment]
I am unable to run it on my own laptop.

**Comment by Hsankesara** [comment]
@shivamsaboo17  not working even after do what you suggested.

**Comment by shivamsaboo17** [comment]
@Hsankesara how did you check?
Try making the above changes and send a Pull Request.

**Comment by shivamsaboo17** [comment]
@Hsankesara it is working after I am making the above changes otherwise it is giving the syntax error.

**Comment by Hsankesara** [comment]
yep syntax error..:disappointed:

**Comment by Hsankesara** [comment]
Maybe I messed up something can you please send PR .

**Comment by Hsankesara** [comment]
So we can check is travis is passing or not
